# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-11 11:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import finance.banking.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='intelligenttimespan',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='banking_intelligent_timespans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='depot',
            name='timespan',
            field=models.ForeignKey(on_delete=models.SET(finance.banking.models.IntelligentTimespan.get_default_intelligent_timespan), related_name='depots', to='banking.IntelligentTimespan'),
        ),
        migrations.AddField(
            model_name='depot',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='banking_depots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='change',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='banking.Account'),
        ),
        migrations.AddField(
            model_name='change',
            name='category',
            field=models.ForeignKey(null=True, on_delete=models.SET(finance.banking.models.Category.get_default_category), related_name='changes', to='banking.Category'),
        ),
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='depot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='banking.Depot'),
        ),
        migrations.AlterUniqueTogether(
            name='movie',
            unique_together=set([('depot', 'account', 'category')]),
        ),
    ]
