# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-14 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import finance.banking.models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_auto_20180414_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depot',
            name='timespan',
            field=models.ForeignKey(null=True, on_delete=models.SET(finance.banking.models.IntelligentTimespan.get_default_intelligent_timespan), related_name='depots', to='banking.IntelligentTimespan'),
        ),
    ]
