# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-14 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_auto_20180414_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depot',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
