# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-26 20:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0008_auto_20180526_2203'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IntelligentTimespan',
            new_name='Timespan',
        ),
    ]
