# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-27 11:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0009_auto_20180526_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timespan',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='banking_timespans', to=settings.AUTH_USER_MODEL),
        ),
    ]
