# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-28 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0011_auto_20180527_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='depot',
            field=models.ForeignKey(default=2, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='banking.Depot'),
            preserve_default=False,
        ),
    ]
