# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-28 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0013_remove_category_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='timespan',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
