# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-28 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0014_timespan_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depot',
            name='timespan',
        ),
    ]
