# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-28 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0016_timespan_depot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timespan',
            name='user',
        ),
    ]
