# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-28 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0017_remove_timespan_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timespan',
            name='depot',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='timespans', to='banking.Depot'),
        ),
    ]
