# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-13 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0020_auto_20180617_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='depot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='banking.Depot'),
        ),
    ]
