# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-28 14:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alternative", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="value",
            name="value",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
