# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-28 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alternative', '0002_auto_20180828_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='alternative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='alternative.Alternative'),
        ),
        migrations.AlterField(
            model_name='value',
            name='alternative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='alternative.Alternative'),
        ),
    ]
