# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-31 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alternative", "0004_flow_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flow",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="value",
            name="date",
            field=models.DateField(),
        ),
    ]
