# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-31 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alternative', '0007_auto_20180831_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='ttwr',
            new_name='twr',
        ),
    ]
