# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-31 15:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alternative", "0009_auto_20180831_1711"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flow",
            name="flow",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name="flow",
            name="value",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
    ]
