# Generated by Django 2.1.5 on 2019-01-06 22:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alternative", "0011_remove_timespan_period"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flow",
            name="value",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
