# Generated by Django 3.0.3 on 2020-03-16 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alternative', '0012_auto_20190106_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flow',
            name='value',
        ),
    ]
