# Generated by Django 3.0.3 on 2020-03-17 11:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("alternative", "0015_stats"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="picture",
            name="cr",
        ),
        migrations.RemoveField(
            model_name="picture",
            name="cs",
        ),
        migrations.RemoveField(
            model_name="picture",
            name="twr",
        ),
    ]
