# Generated by Django 3.0.3 on 2020-03-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alternative", "0016_auto_20200317_1200"),
    ]

    operations = [
        migrations.AlterField(
            model_name="picture",
            name="d",
            field=models.DateTimeField(),
        ),
    ]
