# Generated by Django 3.0.3 on 2020-03-17 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alternative', '0018_auto_20200317_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='d',
            new_name='date',
        ),
    ]
