# Generated by Django 3.0.3 on 2020-03-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alternative", "0019_auto_20200317_1201"),
    ]

    operations = [
        migrations.AddField(
            model_name="picture",
            name="flow",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=18, null=True
            ),
        ),
    ]
