# Generated by Django 3.0.3 on 2020-03-17 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alternative', '0021_auto_20200317_1737'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stats',
        ),
    ]
