# Generated by Django 3.0.3 on 2020-03-18 14:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("alternative", "0025_auto_20200318_1512"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Stats",
        ),
    ]
