# Generated by Django 3.0.3 on 2020-04-01 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alternative', '0027_delete_timespan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternative',
            name='slug',
        ),
    ]
