# Generated by Django 3.0.3 on 2020-08-14 22:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("alternative", "0029_auto_20200815_0008"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="picture",
            name="movie",
        ),
        migrations.RemoveField(
            model_name="alternative",
            name="latest_picture",
        ),
        migrations.RemoveField(
            model_name="depot",
            name="latest_picture",
        ),
        migrations.DeleteModel(
            name="Movie",
        ),
        migrations.DeleteModel(
            name="Picture",
        ),
    ]
