# Generated by Django 4.2.7 on 2023-11-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alternative", "0031_alternative_profit"),
    ]

    operations = [
        migrations.AddField(
            model_name="depot",
            name="value",
            field=models.FloatField(null=True),
        ),
    ]
