# Generated by Django 4.2.7 on 2023-11-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alternative", "0032_depot_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="alternative",
            name="value",
            field=models.FloatField(null=True),
        ),
    ]
