# Generated by Django 4.2.7 on 2023-11-08 22:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("alternative", "0034_remove_alternative_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alternative",
            name="internal_rate_of_return",
        ),
        migrations.RemoveField(
            model_name="alternative",
            name="time_weighted_return",
        ),
    ]
