# Generated by Django 4.2.7 on 2024-02-26 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("overview", "0001_initial"),
        ("alternative", "0035_remove_alternative_internal_rate_of_return_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alternative",
            name="bucket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="overview.bucket",
            ),
        ),
    ]
