# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-10 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0014_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
