# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-23 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0028_asset_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='symbol',
            field=models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('XRP', 'Ripple'), ('BCH', 'Bitcoin Cash'), ('EOS', 'EOS'), ('LTC', 'Litecoin'), ('XLM', 'Stellar'), ('ADA', 'Cardano'), ('TRX', 'TRON'), ('MIOTA', 'IOTA'), ('USDT', 'Tether'), ('NEO', 'NEO'), ('DASH', 'Dash'), ('BNB', 'Binance Coin'), ('XMR', 'Monero'), ('ETC', 'Ethereum Classic'), ('VEN', 'VeChain'), ('XEM', 'NEM'), ('OMG', 'OmiseGO'), ('ONT', 'Ontology'), ('QTUM', 'Qtum'), ('ZEC', 'Zcash'), ('ICX', 'ICON'), ('LSK', 'Lisk'), ('DCR', 'Decred'), ('ZIL', 'Zilliqa'), ('BCN', 'Bytecoin'), ('AE', 'Aeternity'), ('BTG', 'Bitcoin Gold'), ('BTM', 'Bytom'), ('SC', 'Siacoin'), ('ZRX', '0x'), ('XVG', 'Verge'), ('BTS', 'BitShares'), ('STEEM', 'Steem'), ('NANO', 'Nano'), ('REP', 'Augur'), ('MKR', 'Maker'), ('BCD', 'Bitcoin Diamond'), ('DOGE', 'Dogecoin'), ('RHOC', 'RChain'), ('WAVES', 'Waves'), ('WAN', 'Wanchain'), ('GNT', 'Golem'), ('BTCP', 'Bitcoin Private'), ('STRAT', 'Stratis'), ('BAT', 'Basic Attention Token'), ('PPT', 'Populous'), ('DGB', 'DigiByte'), ('HT', 'Huobi Token'), ('KCS', 'KuCoin Shares'), ('SNT', 'Status'), ('NAS', 'Nebulas'), ('WTC', 'Waltonchain'), ('HSR', 'Hshare'), ('IOST', 'IOST'), ('DGD', 'DigixDAO'), ('AION', 'Aion'), ('LRC', 'Loopring'), ('GXS', 'GXChain'), ('CNX', 'Cryptonex'), ('KMD', 'Komodo'), ('BNT', 'Bancor'), ('RDD', 'ReddCoin'), ('ARDR', 'Ardor'), ('GTC', 'Game.com'), ('ARK', 'Ark'), ('MONA', 'MonaCoin'), ('MAID', 'MaidSafeCoin'), ('MOAC', 'MOAC')], max_length=3),
        ),
    ]
