# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-25 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0037_auto_20180625_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='private_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='private_symbol',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
