# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-25 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0038_auto_20180625_1246'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='personalprice',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='personalprice',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='price',
            name='asset_symbol',
        ),
        migrations.DeleteModel(
            name='PersonalPrice',
        ),
    ]
