# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-11 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_auto_20180411_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='timespan',
            name='test',
            field=models.BooleanField(default=False),
        ),
    ]
