# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-11 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crypto", "0003_timespan_test"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timespan",
            name="test",
        ),
    ]
