# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-04 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crypto", "0008_auto_20180604_1425"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="depot",
            name="timespan",
        ),
    ]
