# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-04 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0009_remove_depot_timespan'),
    ]

    operations = [
        migrations.AddField(
            model_name='intelligenttimespan',
            name='depot',
            field=models.ForeignKey(default=0, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='timespans', to='crypto.Depot'),
            preserve_default=False,
        ),
    ]
