# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-12 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crypto", "0015_transaction_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trade",
            name="is_move_trade",
        ),
    ]
