# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-12 19:52
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crypto", "0016_remove_trade_is_move_trade"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="acc_movie",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="test",
                to="crypto.Movie",
            ),
        ),
    ]
