# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-12 20:05
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crypto", "0019_auto_20180612_2159"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="movie",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="undefined_3",
                to="crypto.Movie",
            ),
        ),
    ]
