# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-12 20:15
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crypto", "0020_account_movie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="crypto.Asset",
            ),
        ),
    ]
