# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-14 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crypto", "0022_auto_20180612_2216"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="acc_movie",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="movie",
        ),
    ]
