# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-18 22:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0024_remove_account_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='ba',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='bs',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='prev',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='sa',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='ss',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='td',
        ),
    ]
