# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-19 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crypto", "0025_auto_20180619_0025"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trade",
            name="buy_amount",
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name="trade",
            name="fees",
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name="trade",
            name="sell_amount",
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="fees",
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
    ]
