# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-23 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crypto", "0026_auto_20180619_1931"),
    ]

    operations = [
        migrations.RenameField(
            model_name="asset",
            old_name="symbol",
            new_name="old_symbol",
        ),
    ]
