# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-03 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crypto", "0043_remove_timespan_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="picture",
            name="f",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=18, null=True
            ),
        ),
    ]
