# Generated by Django 3.0.3 on 2020-03-25 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crypto", "0045_auto_20180903_2330"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
