# Generated by Django 3.0.3 on 2020-03-29 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crypto", "0048_auto_20200329_2113"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="depot",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assets2",
                to="crypto.Depot",
            ),
        ),
    ]
