# Generated by Django 3.0.3 on 2020-03-29 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0053_auto_20200329_2150'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('symbol', 'date')},
        ),
        migrations.RemoveField(
            model_name='price',
            name='currency',
        ),
    ]
