# Generated by Django 3.0.3 on 2020-03-30 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crypto", "0057_asset_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trade",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="trades",
                to="crypto.Account",
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="buy_asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="buy_trades",
                to="crypto.Asset",
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="fees_asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="trade_fees",
                to="crypto.Asset",
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="sell_asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sell_trades",
                to="crypto.Asset",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="crypto.Asset",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="from_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="from_transactions",
                to="crypto.Account",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="to_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="to_transactions",
                to="crypto.Account",
            ),
        ),
    ]
