# Generated by Django 3.0.3 on 2020-03-30 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0062_auto_20200330_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='fees',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='fees_asset',
        ),
    ]
