# Generated by Django 3.0.3 on 2020-03-30 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0063_auto_20200330_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAssetStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_stats', to='crypto.Account')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_stats', to='crypto.Asset')),
            ],
        ),
    ]
