# Generated by Django 3.0.3 on 2020-03-30 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0064_accountassetstats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='movie',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
