# Generated by Django 3.0.3 on 2020-04-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0067_coingeckoasset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coingeckoasset',
            name='coingecko_id',
            field=models.CharField(default='', max_length=40, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coingeckoasset',
            name='name',
            field=models.CharField(default='', max_length=40, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coingeckoasset',
            name='symbol',
            field=models.CharField(default='', max_length=5, unique=True),
            preserve_default=False,
        ),
    ]
