# Generated by Django 3.0.3 on 2020-04-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crypto", "0068_auto_20200401_1604"),
    ]

    operations = [
        migrations.AddField(
            model_name="coingeckoasset",
            name="coingecko_symbol",
            field=models.CharField(default="", max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
