# Generated by Django 3.0.3 on 2020-04-02 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0070_remove_coingeckoasset_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trade',
            unique_together={('account', 'date')},
        ),
    ]
