# Generated by Django 3.0.3 on 2020-04-02 17:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crypto", "0071_auto_20200402_1905"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="transaction",
            unique_together={("from_account", "date"), ("to_account", "date")},
        ),
    ]
