# Generated by Django 3.0.3 on 2020-08-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crypto", "0075_auto_20200407_1456"),
    ]

    operations = [
        migrations.AlterField(
            model_name="depot",
            name="current_return",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="depot",
            name="internal_rate_of_return",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="depot",
            name="invested_capital",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="depot",
            name="time_weighted_return",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="depot",
            name="value",
            field=models.FloatField(null=True),
        ),
    ]
