# Generated by Django 4.2.3 on 2023-07-29 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crypto", "0078_auto_20200815_1302"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceFetcher",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fetcher_type",
                    models.CharField(
                        choices=[
                            ("WEBSITE", "Website"),
                            ("SELENIUM", "Selenium"),
                            ("COINGECKO", "CoinGecko"),
                        ],
                        max_length=250,
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                ("error", models.CharField(blank=True, max_length=1000)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_fetchers",
                        to="crypto.asset",
                    ),
                ),
            ],
        ),
    ]
