# Generated by Django 4.2.3 on 2023-07-29 21:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crypto", "0079_pricefetcher"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CoinGeckoAsset",
        ),
    ]
