# Generated by Django 4.2.4 on 2023-08-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crypto", "0080_delete_coingeckoasset"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="top_price",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
