# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-31 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_standarduser_banking_show_balance"),
    ]

    operations = [
        migrations.RenameField(
            model_name="standarduser",
            old_name="banking_show_balance",
            new_name="banking_active",
        ),
    ]
