# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-23 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180603_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='standarduser',
            name='front_page',
            field=models.CharField(choices=[('Banking', 'BANKING'), ('Crypto', 'CRYPTO'), ('Settings', 'SETTINGS')], default='SETTINGS', max_length=8),
        ),
    ]
