# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-23 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_standarduser_front_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="standarduser",
            name="front_page",
            field=models.CharField(
                choices=[
                    ("BANKING", "Banking"),
                    ("CRYPTO", "Crypto"),
                    ("SETTINGS", "Settings"),
                ],
                default="SETTINGS",
                max_length=8,
            ),
        ),
    ]
