# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-27 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20180731_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='standarduser',
            name='alternative_is_active',
            field=models.BooleanField(default=False),
        ),
    ]
