# Generated by Django 2.1.5 on 2019-01-06 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_standarduser_alternative_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="standarduser",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="last name"
            ),
        ),
    ]
