# Generated by Django 3.0.3 on 2020-03-25 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190106_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standarduser',
            name='currency',
        ),
    ]
