# Generated by Django 3.0.3 on 2020-03-25 18:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_remove_standarduser_currency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="standarduser",
            name="alternative_is_active",
        ),
        migrations.RemoveField(
            model_name="standarduser",
            name="banking_is_active",
        ),
        migrations.RemoveField(
            model_name="standarduser",
            name="crypto_is_active",
        ),
    ]
