# Generated by Django 3.0.3 on 2020-03-26 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200325_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standarduser',
            name='slug',
        ),
    ]
