# Generated by Django 3.0.3 on 2020-03-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_remove_standarduser_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="standarduser",
            name="date_format",
            field=models.CharField(
                choices=[
                    ("%d.%m.%Y", "Date.Month.Year"),
                    ("%m/%d/%Y", "Month/Date/Year"),
                ],
                max_length=20,
            ),
        ),
    ]
