# Generated by Django 4.2.3 on 2023-07-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0019_auto_20200815_1247"),
    ]

    operations = [
        migrations.AlterField(
            model_name="standarduser",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Designates that this user has all permissions"
                    " without explicitly assigning them."
                ),
                verbose_name="superuser status",
            ),
        ),
    ]
