# Generated by Django 4.2.7 on 2024-07-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0020_alter_standarduser_is_superuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="standarduser",
            name="front_page",
            field=models.CharField(default="/overview/dashboard/", max_length=200),
        ),
    ]
