# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-02 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_standarduser_crypto_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standarduser',
            old_name='banking_active',
            new_name='banking_is_active',
        ),
    ]
