# Generated by Django 3.0.3 on 2020-07-20 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='date',
        ),
        migrations.AddField(
            model_name='stock',
            name='depot',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='stocks.Depot'),
            preserve_default=False,
        ),
    ]
