# Generated by Django 3.0.3 on 2020-07-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0004_bank_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="depot",
            name="balance",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
    ]
