# Generated by Django 3.0.3 on 2020-07-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_auto_20200724_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='exchange',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
