# Generated by Django 3.0.3 on 2020-07-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0009_auto_20200724_2243"),
    ]

    operations = [
        migrations.AddField(
            model_name="bank",
            name="value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
    ]
