# Generated by Django 3.0.3 on 2020-07-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0012_dividend'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='short_description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
