# Generated by Django 3.0.3 on 2020-07-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0014_auto_20200728_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='sold_total',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
