# Generated by Django 3.0.3 on 2020-07-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0015_stock_sold_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='dividends_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='invested_capital',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='invested_total',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sold_total',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='value',
            field=models.FloatField(null=True),
        ),
    ]
