# Generated by Django 3.0.3 on 2020-08-06 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0019_stock_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceFetcher",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("website", models.CharField(max_length=350)),
                ("target", models.CharField(max_length=250)),
                (
                    "stock",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_fetcher",
                        to="stocks.Stock",
                    ),
                ),
            ],
        ),
    ]
