# Generated by Django 3.0.3 on 2020-08-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0020_pricefetcher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricefetcher',
            name='website',
            field=models.URLField(),
        ),
    ]
