# Generated by Django 4.2.3 on 2023-07-18 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0026_pricefetcher_data_pricefetcher_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricefetcher',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_fetcher', to='stocks.stock'),
        ),
    ]
