# Generated by Django 4.2.3 on 2023-07-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0028_alter_pricefetcher_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricefetcher',
            name='type',
            field=models.CharField(choices=[('WEBSITE', 'Website'), ('SELENIUM', 'Selenium'), ('MARKETSTACK', 'Marketstack')], max_length=250),
        ),
    ]
