# Generated by Django 4.2.3 on 2023-07-27 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0030_pricefetcher_error'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricefetcher',
            old_name='type',
            new_name='fetcher_type',
        ),
    ]
