# Generated by Django 4.2.3 on 2023-08-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0032_remove_pricefetcher_target_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="top_price",
            field=models.FloatField(null=True),
        ),
    ]
