# Generated by Django 4.2.4 on 2023-08-26 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0036_remove_stock_price_remove_stock_top_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="price",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_stocks",
                to="stocks.price",
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="top_price",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="top_price_stocks",
                to="stocks.price",
            ),
        ),
    ]
