# Generated by Django 4.2.7 on 2023-11-12 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0037_stock_price_stock_top_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="price",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="price_stocks",
                to="stocks.price",
            ),
        ),
    ]
