# Generated by Django 5.1.2 on 2024-12-14 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0040_bank_bucket_alter_stock_bucket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trade",
            name="stock_amount",
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
