# Generated by Django 5.1.4 on 2024-12-22 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0044_price_isin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="price",
            name="exchange",
        ),
        migrations.RemoveField(
            model_name="price",
            name="ticker",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="exchange",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="ticker",
        ),
    ]
