# Generated by Django 5.1.11 on 2025-09-28 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0046_alter_price_isin_alter_stock_isin"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pricefetcher",
            options={
                "verbose_name": "Price Fetcher",
                "verbose_name_plural": "Price Fetchers",
            },
        ),
    ]
