# Generated by Django 4.2.7 on 2024-02-26 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("overview", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bucket",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buckets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
