# Generated by Django 4.2.7 on 2024-02-28 21:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("overview", "0002_alter_bucket_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="bucket",
            name="wanted_percentage",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
