# Generated by Django 3.0.3 on 2020-03-25 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_auto_20200325_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
