# Generated by Django 3.0.3 on 2020-03-29 20:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("banking", "0003_remove_category_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="slug",
        ),
    ]
