# Generated by Django 4.2.7 on 2024-07-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banking", "0005_account_bucket"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="changes_count",
            field=models.IntegerField(default=0),
        ),
    ]
