# Generated by Django 4.2.7 on 2024-07-25 07:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("banking", "0006_account_changes_count"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={"ordering": ["-changes_count"]},
        ),
    ]
