# Generated by Django 4.2.7 on 2024-07-30 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banking", "0007_alter_account_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="depot",
            name="most_money_moved_away",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="most_money_moved_away",
                to="banking.account",
            ),
        ),
        migrations.AddField(
            model_name="depot",
            name="most_money_moved_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="most_money_moved_to",
                to="banking.account",
            ),
        ),
    ]
