# Generated by Django 5.1.6 on 2025-02-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0008_depot_most_money_moved_away_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
