# Generated by Django 5.1.5 on 2025-02-21 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0009_account_is_archived"),
    ]

    operations = [
        migrations.AlterField(
            model_name="change",
            name="category",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="changes",
                to="banking.category",
            ),
            preserve_default=False,
        ),
    ]
