# Generated by Django 5.1.11 on 2025-07-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0010_alter_change_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="monthly_budget",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
    ]
