# Generated by Django 5.1.11 on 2025-07-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0011_category_monthly_budget"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="changes_count",
            field=models.IntegerField(default=0),
        ),
    ]
