# Generated by Django 5.1.11 on 2025-07-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0012_category_changes_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="default_date",
            field=models.CharField(
                choices=[("today", "Today"), ("last_transaction", "Last Transaction")],
                default="today",
                max_length=20,
            ),
        ),
    ]
