# Generated by Django 5.1.11 on 2025-09-11 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0013_account_default_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportMap",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("map", models.JSONField()),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_maps",
                        to="banking.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Import Map",
                "verbose_name_plural": "Import Maps",
            },
        ),
    ]
