# Generated by Django 5.1.11 on 2025-09-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0014_importmap"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
