# Generated by Django 5.1.11 on 2025-09-28 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0015_category_is_archived"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComdirectImport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comdirect_api_client_id", models.CharField(max_length=255)),
                ("comdirect_api_client_secret", models.CharField(max_length=255)),
                ("comdirect_1zugangsnummer", models.CharField(max_length=255)),
                ("comdirect_pin", models.CharField(max_length=255)),
                ("comdirect_account_id", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comdirect_import",
                        to="banking.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comdirect Import",
                "verbose_name_plural": "Comdirect Imports",
            },
        ),
        migrations.CreateModel(
            name="ComdirectImportChange",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sha", models.CharField(max_length=64)),
                ("date", models.DateField()),
                ("description", models.TextField()),
                ("change", models.DecimalField(decimal_places=2, max_digits=15)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "comdirect_import",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="banking.comdirectimport",
                    ),
                ),
                (
                    "linked_change",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comdirect_import_changes",
                        to="banking.change",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comdirect Import Change",
                "verbose_name_plural": "Comdirect Import Changes",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
