# Generated by Django 5.1.11 on 2025-09-28 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0016_comdirectimport_comdirectimportchange"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comdirectimport",
            old_name="comdirect_1zugangsnummer",
            new_name="comdirect_zugangsnummer",
        ),
    ]
