# Generated by Django 5.2.7 on 2025-12-02 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "banking",
            "0017_rename_comdirect_1zugangsnummer_comdirectimport_comdirect_zugangsnummer",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ImportMap",
            new_name="CsvImport",
        ),
    ]
