# Generated by Django 5.2.7 on 2025-12-02 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0018_rename_importmap_csvimport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="csvimport",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="csv_import",
                to="banking.account",
            ),
        ),
    ]
